apiVersion: v1
kind: ReplicationController
metadata:
        name: fluentd-app
spec:
        replicas: 2
        selector:
                code: fluentd
        template:
                metadata:
                        name: fluentd-code
                        labels:
                                code: fluentd
                spec:
                        containers:
                                - name: fluentd-c
                                  image: registry/fl-app:2
                                  ports:
                                          - containerPort: 24284
                                  volumeMounts:
                                  - name: fluentd-app-volume-4
                                    mountPath: /etc/td-agent/certs/
                                    readOnly: true
                        volumes:
                            - name: fluentd-app-volume-4
                              secret:
                                secretName: fluentd-aap-secrete
                        serviceAccountName: fluentd-service-account
                        serviceAccount: fluentd-service-account
